[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["package.json", "package-lock.json", "!node_modules/**/*", ".next/**/*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = true 