[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD src/app/"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["package.json", "package-lock.json", "!node_modules/**/*", ".next/**/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 